const api = async (path, options={}) => {
  const response = await fetch(`/api/console/${path}`, { ...options, headers:{"Content-Type":"application/json",...(options.headers||{})} });
  const body = await response.json().catch(()=>({error:"Unexpected response"}));
  if (!response.ok) throw Object.assign(new Error(body.error||"Request failed"),{body,status:response.status});
  return body;
};
const state={dashboard:null,creators:[],current:null};
const $=(s)=>document.querySelector(s); const escape=(v='')=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const notice=(message,error=false)=>{const el=$("#notice");el.textContent=message;el.className=`notice${error?' error':''}`;el.hidden=false;setTimeout(()=>el.hidden=true,5000)};

async function start(){
  try{state.dashboard=await api("dashboard");state.creators=(await api("creators")).creators;renderChrome();renderHome();renderWork();$("#loading").hidden=true;$("#app").hidden=false}
  catch(error){$("#loading").innerHTML=`<div class="loop-mark">∞</div><h1>Access locked</h1><p>${escape(error.message)}</p>`}
}
function renderChrome(){const {user,campaign}=state.dashboard;$("#operator-name").textContent=user.displayName;$("#operator-role").textContent=user.role.replaceAll('_',' ');$("#operator-id").textContent=user.id;$("#campaign-name").textContent=`${campaign.name} · ${campaign.brand_code}`}
function count(...keys){return keys.reduce((n,k)=>n+(state.dashboard.counts[k]||0),0)}
function renderHome(){const d=state.dashboard;$("#home-view").innerHTML=`
  <div class="hero"><span class="eyebrow">CREATOR ON THE SURFACE. OPERATIONS UNDERNEATH.</span><h1>Know what’s next.<br><em>Keep the proof.</em></h1><p>You are working inside ${escape(d.campaign.name)}. Finish the facts, attach the evidence, and send the record to QA. Nothing passes because someone simply says it is done.</p><button class="action" data-go="work">Open creator work</button></div>
  <div class="section-head"><div><h2>Work status</h2><p>Live counts from this campaign. No made-up dashboard numbers.</p></div></div>
  <div class="status-grid"><div class="status-card ready"><small>READY</small><strong>${count('AVAILABLE')}</strong></div><div class="status-card progress"><small>IN PROGRESS</small><strong>${count('IN_PROGRESS')}</strong></div><div class="status-card blocked"><small>BLOCKED / CORRECTION</small><strong>${count('HOLD','CORRECTION_REQUIRED')}</strong></div><div class="status-card qa"><small>AWAITING QA</small><strong>${count('AWAITING_QA')}</strong></div><div class="status-card passed"><small>PASSED</small><strong>${count('PASSED')}</strong></div></div>
  <div class="section-head"><div><h2>Your next action</h2><p>${escape(d.nextAction)}</p></div><button class="action secondary" data-go="work">Continue</button></div>`;
}
function renderWork(){const list=state.creators.map(c=>`<button class="record ${state.current?.id===c.id?'active':''}" data-record="${c.id}"><span class="badge ${c.workflow_status}">${c.workflow_status.replaceAll('_',' ')}</span><strong>${escape(c.id)} · ${escape(c.creator_name)}</strong><small>${escape(c.primary_platform)} · ${escape(c.handle)}</small></button>`).join('');$("#work-view").innerHTML=`<div class="section-head"><div><h2>Creator enrollment</h2><p>First approved workbook workflow: create one permanent creator record, add evidence, then complete QA.</p></div><button class="action" id="new-creator">New creator</button></div><div class="guide"><span><b>AUTO</b>ID & timestamps</span><span><b>SELECT</b>Approved options</span><span><b>INPUT</b>New facts</span><span><b>LOCKED</b>Campaign & history</span><span><b>APPROVAL</b>QA decision</span></div><div class="work-layout"><div class="record-list">${list||'<div class="panel">No creator records yet.</div>'}</div><div id="editor" class="panel"><p class="field-help">Choose a record, or start a new creator enrollment.</p></div></div>`}
const options=(values,current)=>values.map(v=>`<option ${v===current?'selected':''}>${escape(v)}</option>`).join('');
function creatorForm(c={}){const edit=Boolean(c.id);return `<form id="creator-form"><div class="form-grid"><label>Creator ID <input class="locked" value="${escape(c.id||'Assigned automatically')}" disabled><span class="field-help">AUTO · Never recycle or type over this ID.</span></label><label>Campaign <input class="locked" value="${escape(state.dashboard.campaign.name)}" disabled><span class="field-help">LOCKED · Puss-N-Boots is this campaign, not the whole app.</span></label><label>Creator name <input name="creatorName" value="${escape(c.creator_name)}" required><span class="field-help">INPUT · Use the creator’s operating name.</span></label><label>Primary platform <select name="primaryPlatform">${options(['Meta','TikTok','Google','Shopify','Klaviyo','Recharge','Clipster','Other'],c.primary_platform)}</select><span class="field-help">SELECT · Approved list only.</span></label><label>Handle <input name="handle" value="${escape(c.handle)}" required></label><label>Email / contact <input name="contact" value="${escape(c.contact)}" required></label><label>Creator status <select name="creatorStatus">${options(['Not Started','In Progress','Blocked','Ready for Review','Approved','Active','Complete','Archived'],c.creator_status)}</select></label><label>Compensation model <select name="compensationModel">${options(['Performance','Fixed Content Fee','Hybrid','Product Seeding','Performance Bonus','Organic Only','N/A'],c.compensation_model)}</select></label><label>Rights status <select name="rightsStatus">${options(['Not Reviewed','Organic Only','Paid Usage Approved','Expired','Blocked'],c.rights_status)}</select></label><label>Evidence link <input name="evidenceLink" type="url" value="${escape(c.evidence_link)}"><span class="field-help">INPUT · Required for Paid Usage Approved. Never place passwords here.</span></label></div><label>Product / campaign focus <textarea name="productFocus" required>${escape(c.product_focus)}</textarea></label><label>Notes <textarea name="notes">${escape(c.notes)}</textarea></label><div class="form-actions"><button class="action" type="submit">${edit?'Save changes':'Create enrollment'}</button>${edit&&['IN_PROGRESS','CORRECTION_REQUIRED','HOLD'].includes(c.workflow_status)?'<button class="action secondary" type="button" id="submit-qa">Send to QA</button>':''}</div></form>${edit?qaPanel(c):''}`}
function qaPanel(c){const canReview=['OPERATIONS','QA_REVIEWER','APPROVAL_AUTHORITY','ADMINISTRATOR'].includes(state.dashboard.user.role);const checks=Object.entries(state.current?.checklist||{}).map(([k,v])=>`<div class="check ${v?'ok':'no'}">${v?'✓':'✕'} ${escape(k.replace(/([A-Z])/g,' $1'))}</div>`).join('');const history=(state.current?.reviews||[]).map(r=>`<div class="check"><strong>${r.result}</strong> · ${escape(r.reviewer_role)} · ${escape(r.created_at)}<br>${escape(r.notes||'')}</div>`).join('');return `<div class="section-head"><div><h2>QA gate</h2><p>Completion needs evidence and an authorized decision.</p></div></div><div class="checklist">${checks}</div>${c.workflow_status==='AWAITING_QA'&&canReview?`<label>QA notes <textarea id="qa-notes" placeholder="Required for HOLD or CORRECTION REQUIRED"></textarea></label><div class="qa-actions"><button class="pass" data-qa="PASS">PASS</button><button class="hold" data-qa="HOLD">HOLD</button><button class="correction" data-qa="CORRECTION_REQUIRED">CORRECTION REQUIRED</button></div>`:''}${history?`<h3>QA history</h3><div class="checklist">${history}</div>`:''}`}
async function openRecord(id){state.current=await api(`creators/${id}`);renderWork();const c=state.current.creator;$("#editor").innerHTML=creatorForm(c);bindForm(c)}
function bindForm(c={}){$("#creator-form").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget;const submit=form.querySelector('[type="submit"]');if(submit.disabled)return;submit.disabled=true;const body=Object.fromEntries(new FormData(form));try{if(c.id){body.version=c.version;await api(`creators/${c.id}`,{method:'PATCH',body:JSON.stringify(body)})}else await api('creators',{method:'POST',body:JSON.stringify(body)});notice('Saved. The audit trail was updated.');await reload('work')}catch(err){submit.disabled=false;notice(err.message,true)}});$("#submit-qa")?.addEventListener('click',async event=>{const button=event.currentTarget;if(button.disabled)return;button.disabled=true;try{await api(`creators/${c.id}`,{method:'PATCH',body:JSON.stringify({action:'AWAITING_QA',version:c.version})});notice('Sent to QA. The record is now locked for review.');await reload('work')}catch(err){button.disabled=false;notice(err.message,true)}});document.querySelectorAll('[data-qa]').forEach(btn=>btn.addEventListener('click',async()=>{if(btn.disabled)return;document.querySelectorAll('[data-qa]').forEach(button=>button.disabled=true);try{await api(`qa/${c.id}`,{method:'POST',body:JSON.stringify({result:btn.dataset.qa,notes:$("#qa-notes").value,version:c.version})});notice(`QA result saved: ${btn.dataset.qa.replaceAll('_',' ')}`);await reload('work')}catch(err){document.querySelectorAll('[data-qa]').forEach(button=>button.disabled=false);notice(err.message,true)}}))}
async function renderAudit(){const {events}=await api('audit');$("#audit-view").innerHTML=`<div class="section-head"><div><h2>Audit trail</h2><p>Operators cannot erase this history from the console.</p></div></div><div class="panel audit-wrap"><table class="audit-table"><thead><tr><th>WHEN</th><th>OPERATOR</th><th>ACTION</th><th>RECORD</th><th>CHANGE</th></tr></thead><tbody>${events.map(e=>`<tr><td>${escape(e.created_at)}</td><td>${escape(e.operator_name)}<br>${escape(e.operator_role)}</td><td>${escape(e.action)}</td><td>${escape(e.object_id)}</td><td>${escape(e.previous_value||'—')} → ${escape(e.new_value||'—')}</td></tr>`).join('')}</tbody></table></div>`}
async function reload(view){state.dashboard=await api('dashboard');state.creators=(await api('creators')).creators;state.current=null;renderHome();renderWork();show(view)}
function show(view){document.querySelectorAll('.view').forEach(v=>v.hidden=true);$(`#${view}-view`).hidden=false;document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='audit')renderAudit();$('.sidebar').classList.remove('open')}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)show(go.dataset.go);const nav=e.target.closest('[data-view]');if(nav)show(nav.dataset.view);const rec=e.target.closest('[data-record]');if(rec)openRecord(rec.dataset.record);if(e.target.id==='new-creator'){$('#editor').innerHTML=creatorForm();bindForm()}});$('#menu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));start();
